name: Build Arch ISO

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      dev:
        description: "Run as development?"
        type: boolean
        required: true
        default: false
        
        
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=$(date +'%Y.%m.%d')" >>$GITHUB_ENV

      - name: Run build-iso script
        run: bash build-iso
        env:
          DATE: ${{ env.DATE }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'true' }}
        with:
          name: Arch Linux ${{ env.DATE }}
          path: "archlinux-${{ env.DATE }}-x86_64.iso"

      - name: Create tag and release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'false') }}
        with:
          name: Arch Linux ${{ env.DATE }}
          tag: ${{ env.DATE }}
          commit: main
          bodyFile: RELEASE.md
          artifacts: "archlinux-${{ env.DATE }}-x86_64.iso"
          token: ${{ secrets.GITHUB_TOKEN }}
